package com.developersbreach.hangman.ui.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

enum class ThemePaletteId {
    ORIGINAL,
    GRAPHITE,
    EMERALD,
    NAVY,
    CORAL,
    AMBER,
    LAVENDER,
    TEAL,
    BLOSSOM,
}

private val originalPalette = ThemePalette(
    id = ThemePaletteId.ORIGINAL,
    displayName = "Original",
    light = PaletteTones(
        primary = Color(0xFF9CF4FF),
        onPrimary = Color(0xFF0C2B2F),
        primaryContainer = Color(0xFFCBFBFF),
        onPrimaryContainer = Color(0xFF001F23),
        secondary = Color(0xFF6ABBC5),
        onSecondary = Color(0xFF0D2A2E),
        secondaryContainer = Color(0xFFBCEEF4),
        onSecondaryContainer = Color(0xFF072125),
        tertiary = Color(0xFF7FAFBE),
        onTertiary = Color(0xFF102129),
        tertiaryContainer = Color(0xFFD0EBF3),
        onTertiaryContainer = Color(0xFF0D1D25),
        background = Color(0xFF1B2425),
        onBackground = Color(0xFFDDEBEC),
        surface = Color(0xFF212C2E),
        onSurface = Color(0xFFD2E5E7),
        surfaceVariant = Color(0xFF2C3A3D),
        onSurfaceVariant = Color(0xFFB1C7CB),
        outline = Color(0xFF7E969A),
        outlineVariant = Color(0xFF3A4A4E),
        inverseSurface = Color(0xFFD2E5E7),
        inverseOnSurface = Color(0xFF1C2A2D),
        surfaceDim = Color(0xFF1A2526),
        surfaceBright = Color(0xFF2D393C),
        surfaceContainerLowest = Color(0xFF11191B),
        surfaceContainerLow = Color(0xFF1A2527),
        surfaceContainer = Color(0xFF212D2F),
        surfaceContainerHigh = Color(0xFF283538),
        surfaceContainerHighest = Color(0xFF2F3D41),
    ),
    dark = PaletteTones(
        primary = Color(0xFFFFA29C),
        onPrimary = Color(0xFF330A07),
        primaryContainer = Color(0xFF5C1713),
        onPrimaryContainer = Color(0xFFFFDAD6),
        secondary = Color(0xFFF3ACA8),
        onSecondary = Color(0xFF32100D),
        secondaryContainer = Color(0xFF5A2320),
        onSecondaryContainer = Color(0xFFFFDAD7),
        tertiary = Color(0xFFE7B3A4),
        onTertiary = Color(0xFF32150F),
        tertiaryContainer = Color(0xFF5A2B21),
        onTertiaryContainer = Color(0xFFFFDCCF),
        background = Color(0xFF221918),
        onBackground = Color(0xFFE9DAD9),
        surface = Color(0xFF312423),
        onSurface = Color(0xFFECD9D8),
        surfaceVariant = Color(0xFF463534),
        onSurfaceVariant = Color(0xFFCFB8B6),
        outline = Color(0xFF9A7F7D),
        outlineVariant = Color(0xFF5E4846),
        inverseSurface = Color(0xFFECD9D8),
        inverseOnSurface = Color(0xFF2A1E1D),
        surfaceDim = Color(0xFF221918),
        surfaceBright = Color(0xFF3B2D2C),
        surfaceContainerLowest = Color(0xFF160F0F),
        surfaceContainerLow = Color(0xFF231918),
        surfaceContainer = Color(0xFF2B1F1E),
        surfaceContainerHigh = Color(0xFF342726),
        surfaceContainerHighest = Color(0xFF3C2F2E),
    ),
    previewColor = Color(0xFFFFA29C),
)

data class PaletteTones(
    val primary: Color,
    val onPrimary: Color,
    val primaryContainer: Color,
    val onPrimaryContainer: Color,
    val secondary: Color,
    val onSecondary: Color,
    val secondaryContainer: Color,
    val onSecondaryContainer: Color,
    val tertiary: Color,
    val onTertiary: Color,
    val tertiaryContainer: Color,
    val onTertiaryContainer: Color,
    val background: Color,
    val onBackground: Color,
    val surface: Color,
    val onSurface: Color,
    val surfaceVariant: Color,
    val onSurfaceVariant: Color,
    val outline: Color,
    val outlineVariant: Color,
    val inverseSurface: Color,
    val inverseOnSurface: Color,
    val surfaceDim: Color,
    val surfaceBright: Color,
    val surfaceContainerLowest: Color,
    val surfaceContainerLow: Color,
    val surfaceContainer: Color,
    val surfaceContainerHigh: Color,
    val surfaceContainerHighest: Color,
)

data class ThemePalette(
    val id: ThemePaletteId,
    val displayName: String,
    val light: PaletteTones,
    val dark: PaletteTones,
    val previewColor: Color,
)

private val graphitePalette = ThemePalette(
    id = ThemePaletteId.GRAPHITE,
    displayName = "Graphite",
    light = PaletteTones(
        primary = Color(0xFF2F2924),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFDCD3CA),
        onPrimaryContainer = Color(0xFF1A130F),
        secondary = Color(0xFF4D4640),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFE0D6CD),
        onSecondaryContainer = Color(0xFF1F1813),
        tertiary = Color(0xFF6C6157),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFFF0DED0),
        onTertiaryContainer = Color(0xFF261A12),
        background = Color(0xFFF4ECE4),
        onBackground = Color(0xFF21160F),
        surface = Color(0xFFEBE1D8),
        onSurface = Color(0xFF21160F),
        surfaceVariant = Color(0xFFD7C9BF),
        onSurfaceVariant = Color(0xFF4F3F35),
        outline = Color(0xFF807064),
        outlineVariant = Color(0xFFC8B8AE),
        inverseSurface = Color(0xFF342820),
        inverseOnSurface = Color(0xFFFAEFE6),
        surfaceDim = Color(0xFFE3D8D0),
        surfaceBright = Color(0xFFF9F1EA),
        surfaceContainerLowest = Color(0xFFFFFBF7),
        surfaceContainerLow = Color(0xFFF5EBE3),
        surfaceContainer = Color(0xFFEEE3DB),
        surfaceContainerHigh = Color(0xFFE7DDD5),
        surfaceContainerHighest = Color(0xFFE0D6CE),
    ),
    dark = PaletteTones(
        primary = Color(0xFFD0C4B9),
        onPrimary = Color(0xFF2B241F),
        primaryContainer = Color(0xFF413933),
        onPrimaryContainer = Color(0xFFEDE1D6),
        secondary = Color(0xFFB8ACA1),
        onSecondary = Color(0xFF2D2621),
        secondaryContainer = Color(0xFF39322C),
        onSecondaryContainer = Color(0xFFE4D9CF),
        tertiary = Color(0xFF9F9286),
        onTertiary = Color(0xFF2E261F),
        tertiaryContainer = Color(0xFF4A4038),
        onTertiaryContainer = Color(0xFFF2E5D9),
        background = Color(0xFF18110D),
        onBackground = Color(0xFFEFE1D8),
        surface = Color(0xFF211712),
        onSurface = Color(0xFFEFE1D8),
        surfaceVariant = Color(0xFF4D3C34),
        onSurfaceVariant = Color(0xFFD7C6BD),
        outline = Color(0xFF9A8A80),
        outlineVariant = Color(0xFF4D3C34),
        inverseSurface = Color(0xFFF2E4DA),
        inverseOnSurface = Color(0xFF342820),
        surfaceDim = Color(0xFF18110D),
        surfaceBright = Color(0xFF3A2C24),
        surfaceContainerLowest = Color(0xFF120C08),
        surfaceContainerLow = Color(0xFF18110D),
        surfaceContainer = Color(0xFF1F150F),
        surfaceContainerHigh = Color(0xFF261C16),
        surfaceContainerHighest = Color(0xFF2E241D),
    ),
    previewColor = Color(0xFF2F2924),
)

private val emeraldPalette = ThemePalette(
    id = ThemePaletteId.EMERALD,
    displayName = "Emerald",
    light = PaletteTones(
        primary = Color(0xFF1F6D54),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFA8DCC4),
        onPrimaryContainer = Color(0xFF0A251A),
        secondary = Color(0xFF3D5F4F),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFC9EBD9),
        onSecondaryContainer = Color(0xFF122820),
        tertiary = Color(0xFF3A6F69),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFFBDE6E0),
        onTertiaryContainer = Color(0xFF082B28),
        background = Color(0xFFF1F7F3),
        onBackground = Color(0xFF0F1F18),
        surface = Color(0xFFE6EFEA),
        onSurface = Color(0xFF0F1F18),
        surfaceVariant = Color(0xFFC6D8CE),
        onSurfaceVariant = Color(0xFF384B41),
        outline = Color(0xFF62766A),
        outlineVariant = Color(0xFFBBD0C4),
        inverseSurface = Color(0xFF22342C),
        inverseOnSurface = Color(0xFFDDEBE3),
        surfaceDim = Color(0xFFDCE5E0),
        surfaceBright = Color(0xFFF7FCF9),
        surfaceContainerLowest = Color(0xFFFBFFFD),
        surfaceContainerLow = Color(0xFFECF5EF),
        surfaceContainer = Color(0xFFE4EDE7),
        surfaceContainerHigh = Color(0xFFDDE6E0),
        surfaceContainerHighest = Color(0xFFD5DED8),
    ),
    dark = PaletteTones(
        primary = Color(0xFF8FD4B8),
        onPrimary = Color(0xFF00382A),
        primaryContainer = Color(0xFF145141),
        onPrimaryContainer = Color(0xFFA8F2D0),
        secondary = Color(0xFFA6D5BE),
        onSecondary = Color(0xFF0F3325),
        secondaryContainer = Color(0xFF264C3A),
        onSecondaryContainer = Color(0xFFBEEFD5),
        tertiary = Color(0xFF91D5CE),
        onTertiary = Color(0xFF003734),
        tertiaryContainer = Color(0xFF20524E),
        onTertiaryContainer = Color(0xFFAAF0EA),
        background = Color(0xFF0C1B15),
        onBackground = Color(0xFFDDEBE2),
        surface = Color(0xFF13241D),
        onSurface = Color(0xFFDDEBE2),
        surfaceVariant = Color(0xFF304038),
        onSurfaceVariant = Color(0xFFBFD2C7),
        outline = Color(0xFF879A8F),
        outlineVariant = Color(0xFF304038),
        inverseSurface = Color(0xFFE4F2E9),
        inverseOnSurface = Color(0xFF1A2C24),
        surfaceDim = Color(0xFF0C1B15),
        surfaceBright = Color(0xFF25352E),
        surfaceContainerLowest = Color(0xFF07120E),
        surfaceContainerLow = Color(0xFF0D1914),
        surfaceContainer = Color(0xFF14211C),
        surfaceContainerHigh = Color(0xFF1C2923),
        surfaceContainerHighest = Color(0xFF24322B),
    ),
    previewColor = Color(0xFF1F6D54),
)

private val navyPalette = ThemePalette(
    id = ThemePaletteId.NAVY,
    displayName = "Navy",
    light = PaletteTones(
        primary = Color(0xFF214A86),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFBFD4FF),
        onPrimaryContainer = Color(0xFF0B2651),
        secondary = Color(0xFF3D5F94),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFD7E3FF),
        onSecondaryContainer = Color(0xFF132D59),
        tertiary = Color(0xFF2E5A9A),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFFC9DEFF),
        onTertiaryContainer = Color(0xFF0A2F5E),
        background = Color(0xFFEFF3FB),
        onBackground = Color(0xFF101931),
        surface = Color(0xFFE4E8F5),
        onSurface = Color(0xFF101931),
        surfaceVariant = Color(0xFFCCD2E5),
        onSurfaceVariant = Color(0xFF3B4460),
        outline = Color(0xFF5D6684),
        outlineVariant = Color(0xFFC1C7DA),
        inverseSurface = Color(0xFF24304A),
        inverseOnSurface = Color(0xFFDEE3F4),
        surfaceDim = Color(0xFFDADFEB),
        surfaceBright = Color(0xFFF6F9FF),
        surfaceContainerLowest = Color(0xFFFAFCFF),
        surfaceContainerLow = Color(0xFFEDF1FA),
        surfaceContainer = Color(0xFFE4E9F5),
        surfaceContainerHigh = Color(0xFFDCE1ED),
        surfaceContainerHighest = Color(0xFFD3D9E6),
    ),
    dark = PaletteTones(
        primary = Color(0xFF9FC2FF),
        onPrimary = Color(0xFF002F65),
        primaryContainer = Color(0xFF204D87),
        onPrimaryContainer = Color(0xFFCCE1FF),
        secondary = Color(0xFFB6CBFF),
        onSecondary = Color(0xFF0A2F63),
        secondaryContainer = Color(0xFF254776),
        onSecondaryContainer = Color(0xFFDCE6FF),
        tertiary = Color(0xFFAEC9FF),
        onTertiary = Color(0xFF083062),
        tertiaryContainer = Color(0xFF234A85),
        onTertiaryContainer = Color(0xFFD7E3FF),
        background = Color(0xFF0D1425),
        onBackground = Color(0xFFDDE3F4),
        surface = Color(0xFF151D2F),
        onSurface = Color(0xFFDDE3F4),
        surfaceVariant = Color(0xFF323B55),
        onSurfaceVariant = Color(0xFFC1C7DF),
        outline = Color(0xFF8A92AC),
        outlineVariant = Color(0xFF323B55),
        inverseSurface = Color(0xFFE4E9FA),
        inverseOnSurface = Color(0xFF1F2740),
        surfaceDim = Color(0xFF0D1425),
        surfaceBright = Color(0xFF273049),
        surfaceContainerLowest = Color(0xFF070D1B),
        surfaceContainerLow = Color(0xFF0D1423),
        surfaceContainer = Color(0xFF141B2B),
        surfaceContainerHigh = Color(0xFF1C2334),
        surfaceContainerHighest = Color(0xFF242C3D),
    ),
    previewColor = Color(0xFF214A86),
)

private val coralPalette = ThemePalette(
    id = ThemePaletteId.CORAL,
    displayName = "Coral",
    light = PaletteTones(
        primary = Color(0xFFB43633),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFFFDAD3),
        onPrimaryContainer = Color(0xFF410006),
        secondary = Color(0xFF8F4B3F),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFFFDAD2),
        onSecondaryContainer = Color(0xFF381912),
        tertiary = Color(0xFF8F5133),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFFFFDCC8),
        onTertiaryContainer = Color(0xFF341204),
        background = Color(0xFFFFF3EF),
        onBackground = Color(0xFF2F0C0A),
        surface = Color(0xFFFFE7E1),
        onSurface = Color(0xFF2F0C0A),
        surfaceVariant = Color(0xFFF4C7BF),
        onSurfaceVariant = Color(0xFF5B2D26),
        outline = Color(0xFF8E4B41),
        outlineVariant = Color(0xFFE5B7AF),
        inverseSurface = Color(0xFF40211C),
        inverseOnSurface = Color(0xFFFFECE7),
        surfaceDim = Color(0xFFEED6D1),
        surfaceBright = Color(0xFFFFF8F5),
        surfaceContainerLowest = Color(0xFFFCF7F4),
        surfaceContainerLow = Color(0xFFFFEDEA),
        surfaceContainer = Color(0xFFFFE3DE),
        surfaceContainerHigh = Color(0xFFFFD8D3),
        surfaceContainerHighest = Color(0xFFFFCEC9),
    ),
    dark = PaletteTones(
        primary = Color(0xFFFFB4A8),
        onPrimary = Color(0xFF68000C),
        primaryContainer = Color(0xFF8E1F1F),
        onPrimaryContainer = Color(0xFFFFDAD3),
        secondary = Color(0xFFFFB4A5),
        onSecondary = Color(0xFF4D1F14),
        secondaryContainer = Color(0xFF6C3529),
        onSecondaryContainer = Color(0xFFFFDAD2),
        tertiary = Color(0xFFFFB68B),
        onTertiary = Color(0xFF4E2500),
        tertiaryContainer = Color(0xFF703900),
        onTertiaryContainer = Color(0xFFFFDCBC),
        background = Color(0xFF2F1613),
        onBackground = Color(0xFFFFEDE7),
        surface = Color(0xFF3A1D19),
        onSurface = Color(0xFFFFEDE7),
        surfaceVariant = Color(0xFF5E342D),
        onSurfaceVariant = Color(0xFFF4C7BF),
        outline = Color(0xFFA7736A),
        outlineVariant = Color(0xFF5E342D),
        inverseSurface = Color(0xFFFFEDEA),
        inverseOnSurface = Color(0xFF442320),
        surfaceDim = Color(0xFF2F1613),
        surfaceBright = Color(0xFF4C2C27),
        surfaceContainerLowest = Color(0xFF230C0A),
        surfaceContainerLow = Color(0xFF2F1411),
        surfaceContainer = Color(0xFF361B18),
        surfaceContainerHigh = Color(0xFF3E231F),
        surfaceContainerHighest = Color(0xFF472C27),
    ),
    previewColor = Color(0xFFB43633),
)

private val amberPalette = ThemePalette(
    id = ThemePaletteId.AMBER,
    displayName = "Amber",
    light = PaletteTones(
        primary = Color(0xFF9C5800),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFFFDDB1),
        onPrimaryContainer = Color(0xFF321300),
        secondary = Color(0xFF7A5B2E),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFFFDEB8),
        onSecondaryContainer = Color(0xFF2B1804),
        tertiary = Color(0xFF6B5F27),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFFF5E39A),
        onTertiaryContainer = Color(0xFF211C00),
        background = Color(0xFFFFF5E7),
        onBackground = Color(0xFF2C1600),
        surface = Color(0xFFFFEAD2),
        onSurface = Color(0xFF2C1600),
        surfaceVariant = Color(0xFFE4CBA9),
        onSurfaceVariant = Color(0xFF574025),
        outline = Color(0xFF8B6A3E),
        outlineVariant = Color(0xFFD7BC94),
        inverseSurface = Color(0xFF423019),
        inverseOnSurface = Color(0xFFFFEED9),
        surfaceDim = Color(0xFFEED9C1),
        surfaceBright = Color(0xFFFFF8EE),
        surfaceContainerLowest = Color(0xFFFFFBF5),
        surfaceContainerLow = Color(0xFFFFEFE0),
        surfaceContainer = Color(0xFFFFE4D0),
        surfaceContainerHigh = Color(0xFFFFD9C0),
        surfaceContainerHighest = Color(0xFFFFCEB1),
    ),
    dark = PaletteTones(
        primary = Color(0xFFFFB860),
        onPrimary = Color(0xFF4F2500),
        primaryContainer = Color(0xFF713700),
        onPrimaryContainer = Color(0xFFFFDDB1),
        secondary = Color(0xFFE5C08D),
        onSecondary = Color(0xFF3B2800),
        secondaryContainer = Color(0xFF5A3C12),
        onSecondaryContainer = Color(0xFFFFDEB8),
        tertiary = Color(0xFFD9C879),
        onTertiary = Color(0xFF332600),
        tertiaryContainer = Color(0xFF4D410A),
        onTertiaryContainer = Color(0xFFF5E39A),
        background = Color(0xFF24160A),
        onBackground = Color(0xFFFFEBD3),
        surface = Color(0xFF312114),
        onSurface = Color(0xFFFFEBD3),
        surfaceVariant = Color(0xFF4F3A22),
        onSurfaceVariant = Color(0xFFE4CBA9),
        outline = Color(0xFFAA8758),
        outlineVariant = Color(0xFF4F3A22),
        inverseSurface = Color(0xFFFFEBD7),
        inverseOnSurface = Color(0xFF3F2C16),
        surfaceDim = Color(0xFF24160A),
        surfaceBright = Color(0xFF44311F),
        surfaceContainerLowest = Color(0xFF190D04),
        surfaceContainerLow = Color(0xFF22140A),
        surfaceContainer = Color(0xFF2C1D11),
        surfaceContainerHigh = Color(0xFF35251A),
        surfaceContainerHighest = Color(0xFF3E2E23),
    ),
    previewColor = Color(0xFF9C5800),
)

private val lavenderPalette = ThemePalette(
    id = ThemePaletteId.LAVENDER,
    displayName = "Lavender",
    light = PaletteTones(
        primary = Color(0xFF6E56B6),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFEBDCFF),
        onPrimaryContainer = Color(0xFF24005B),
        secondary = Color(0xFF655A77),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFEBDCFF),
        onSecondaryContainer = Color(0xFF201634),
        tertiary = Color(0xFF815A71),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFFFFD8E7),
        onTertiaryContainer = Color(0xFF341126),
        background = Color(0xFFF6F1FF),
        onBackground = Color(0xFF21163A),
        surface = Color(0xFFEAE0FF),
        onSurface = Color(0xFF21163A),
        surfaceVariant = Color(0xFFD6CCF5),
        onSurfaceVariant = Color(0xFF443864),
        outline = Color(0xFF6D5F8C),
        outlineVariant = Color(0xFFCABFE9),
        inverseSurface = Color(0xFF332758),
        inverseOnSurface = Color(0xFFF2EAFF),
        surfaceDim = Color(0xFFDDD3F1),
        surfaceBright = Color(0xFFFBF6FF),
        surfaceContainerLowest = Color(0xFFFFFBFF),
        surfaceContainerLow = Color(0xFFF0E6FF),
        surfaceContainer = Color(0xFFE5DCFF),
        surfaceContainerHigh = Color(0xFFDBD1F6),
        surfaceContainerHighest = Color(0xFFD0C7EC),
    ),
    dark = PaletteTones(
        primary = Color(0xFFCFBCFF),
        onPrimary = Color(0xFF371E71),
        primaryContainer = Color(0xFF4E379D),
        onPrimaryContainer = Color(0xFFEBDCFF),
        secondary = Color(0xFFCEC2DB),
        onSecondary = Color(0xFF322B41),
        secondaryContainer = Color(0xFF4A4459),
        onSecondaryContainer = Color(0xFFEBDCFF),
        tertiary = Color(0xFFEFB8D5),
        onTertiary = Color(0xFF4B2538),
        tertiaryContainer = Color(0xFF663D50),
        onTertiaryContainer = Color(0xFFFFD8E7),
        background = Color(0xFF1A122B),
        onBackground = Color(0xFFECE3FF),
        surface = Color(0xFF221936),
        onSurface = Color(0xFFECE3FF),
        surfaceVariant = Color(0xFF40365A),
        onSurfaceVariant = Color(0xFFD6CCF5),
        outline = Color(0xFF9C90B8),
        outlineVariant = Color(0xFF40365A),
        inverseSurface = Color(0xFFF0E7FF),
        inverseOnSurface = Color(0xFF31265B),
        surfaceDim = Color(0xFF1A122B),
        surfaceBright = Color(0xFF372E50),
        surfaceContainerLowest = Color(0xFF120B22),
        surfaceContainerLow = Color(0xFF191129),
        surfaceContainer = Color(0xFF211833),
        surfaceContainerHigh = Color(0xFF29203C),
        surfaceContainerHighest = Color(0xFF322745),
    ),
    previewColor = Color(0xFF6E56B6),
)

private val tealPalette = ThemePalette(
    id = ThemePaletteId.TEAL,
    displayName = "Teal",
    light = PaletteTones(
        primary = Color(0xFF00687C),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFF9EEFFF),
        onPrimaryContainer = Color(0xFF001F26),
        secondary = Color(0xFF4C6268),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFCDE7ED),
        onSecondaryContainer = Color(0xFF062026),
        tertiary = Color(0xFF50607D),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFFD5E3FF),
        onTertiaryContainer = Color(0xFF0C1C37),
        background = Color(0xFFECF7F9),
        onBackground = Color(0xFF061C22),
        surface = Color(0xFFE0F0F3),
        onSurface = Color(0xFF061C22),
        surfaceVariant = Color(0xFFC1DCE1),
        onSurfaceVariant = Color(0xFF31474D),
        outline = Color(0xFF576F75),
        outlineVariant = Color(0xFFB5CDD2),
        inverseSurface = Color(0xFF1F3136),
        inverseOnSurface = Color(0xFFD8E8EB),
        surfaceDim = Color(0xFFD5E6E9),
        surfaceBright = Color(0xFFF3FDFF),
        surfaceContainerLowest = Color(0xFFF7FEFF),
        surfaceContainerLow = Color(0xFFE7F5F7),
        surfaceContainer = Color(0xFFDDECEE),
        surfaceContainerHigh = Color(0xFFD3E2E4),
        surfaceContainerHighest = Color(0xFFC9D8DA),
    ),
    dark = PaletteTones(
        primary = Color(0xFF7DD0E4),
        onPrimary = Color(0xFF003640),
        primaryContainer = Color(0xFF005165),
        onPrimaryContainer = Color(0xFF9EEFFF),
        secondary = Color(0xFFB1CBD2),
        onSecondary = Color(0xFF1B353A),
        secondaryContainer = Color(0xFF324A50),
        onSecondaryContainer = Color(0xFFCDE7ED),
        tertiary = Color(0xFFB6C7E4),
        onTertiary = Color(0xFF1D2D41),
        tertiaryContainer = Color(0xFF354559),
        onTertiaryContainer = Color(0xFFD5E3FF),
        background = Color(0xFF081A1F),
        onBackground = Color(0xFFD6EBEE),
        surface = Color(0xFF10242A),
        onSurface = Color(0xFFD6EBEE),
        surfaceVariant = Color(0xFF294048),
        onSurfaceVariant = Color(0xFFBED6DB),
        outline = Color(0xFF859CA2),
        outlineVariant = Color(0xFF294048),
        inverseSurface = Color(0xFFEEF9FB),
        inverseOnSurface = Color(0xFF1B2F34),
        surfaceDim = Color(0xFF081A1F),
        surfaceBright = Color(0xFF23363C),
        surfaceContainerLowest = Color(0xFF041115),
        surfaceContainerLow = Color(0xFF09181C),
        surfaceContainer = Color(0xFF0F1F24),
        surfaceContainerHigh = Color(0xFF16262C),
        surfaceContainerHighest = Color(0xFF1E2E34),
    ),
    previewColor = Color(0xFF00687C),
)

private val blossomPalette = ThemePalette(
    id = ThemePaletteId.BLOSSOM,
    displayName = "Blossom",
    light = PaletteTones(
        primary = Color(0xFF9C3D73),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFFFD8E7),
        onPrimaryContainer = Color(0xFF3A0022),
        secondary = Color(0xFF775A65),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFFFD8E6),
        onSecondaryContainer = Color(0xFF2D1620),
        tertiary = Color(0xFF7F5462),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFFFFD9E2),
        onTertiaryContainer = Color(0xFF32111D),
        background = Color(0xFFFFF2F7),
        onBackground = Color(0xFF2F1220),
        surface = Color(0xFFFFE7EF),
        onSurface = Color(0xFF2F1220),
        surfaceVariant = Color(0xFFF0C6D4),
        onSurfaceVariant = Color(0xFF5A2F3B),
        outline = Color(0xFF8A5666),
        outlineVariant = Color(0xFFE3B5C4),
        inverseSurface = Color(0xFF412632),
        inverseOnSurface = Color(0xFFFFE9F1),
        surfaceDim = Color(0xFFEED6DF),
        surfaceBright = Color(0xFFFFF8FB),
        surfaceContainerLowest = Color(0xFFFFFBFD),
        surfaceContainerLow = Color(0xFFF5EAF1),
        surfaceContainer = Color(0xFFECDDE5),
        surfaceContainerHigh = Color(0xFFE2D1DA),
        surfaceContainerHighest = Color(0xFFD7C6D0),
    ),
    dark = PaletteTones(
        primary = Color(0xFFFFB0D7),
        onPrimary = Color(0xFF5E103A),
        primaryContainer = Color(0xFF7D2853),
        onPrimaryContainer = Color(0xFFFFD8E7),
        secondary = Color(0xFFE5BCC7),
        onSecondary = Color(0xFF442832),
        secondaryContainer = Color(0xFF5D3F48),
        onSecondaryContainer = Color(0xFFFFD8E6),
        tertiary = Color(0xFFE3BDC7),
        onTertiary = Color(0xFF452631),
        tertiaryContainer = Color(0xFF5E3D47),
        onTertiaryContainer = Color(0xFFFFD9E2),
        background = Color(0xFF2B131F),
        onBackground = Color(0xFFFFE9F2),
        surface = Color(0xFF381A26),
        onSurface = Color(0xFFFFE9F2),
        surfaceVariant = Color(0xFF5C3441),
        onSurfaceVariant = Color(0xFFF0C6D4),
        outline = Color(0xFFA77484),
        outlineVariant = Color(0xFF5C3441),
        inverseSurface = Color(0xFFFFE9F1),
        inverseOnSurface = Color(0xFF44212D),
        surfaceDim = Color(0xFF2B131F),
        surfaceBright = Color(0xFF4A2834),
        surfaceContainerLowest = Color(0xFF1F0915),
        surfaceContainerLow = Color(0xFF2A111D),
        surfaceContainer = Color(0xFF311823),
        surfaceContainerHigh = Color(0xFF39202B),
        surfaceContainerHighest = Color(0xFF422835),
    ),
    previewColor = Color(0xFF9C3D73),
)

object ThemePalettes {
    val all: List<ThemePalette> = listOf(
        originalPalette,
        coralPalette,
        blossomPalette,
        amberPalette,
        graphitePalette,
        emeraldPalette,
        tealPalette,
        navyPalette,
        lavenderPalette,
    )

    val default: ThemePalette = originalPalette

    private val paletteById = all.associateBy { it.id }

    fun byId(id: ThemePaletteId): ThemePalette = paletteById[id] ?: default
}

internal fun ThemePalette.toLightColorScheme(): ColorScheme = lightColorScheme(
    primary = light.primary,
    onPrimary = light.onPrimary,
    primaryContainer = light.primaryContainer,
    onPrimaryContainer = light.onPrimaryContainer,
    secondary = light.secondary,
    onSecondary = light.onSecondary,
    secondaryContainer = light.secondaryContainer,
    onSecondaryContainer = light.onSecondaryContainer,
    tertiary = light.tertiary,
    onTertiary = light.onTertiary,
    tertiaryContainer = light.tertiaryContainer,
    onTertiaryContainer = light.onTertiaryContainer,
    background = light.background,
    onBackground = light.onBackground,
    surface = light.surface,
    onSurface = light.onSurface,
    surfaceVariant = light.surfaceVariant,
    onSurfaceVariant = light.onSurfaceVariant,
    outline = light.outline,
    outlineVariant = light.outlineVariant,
    scrim = scrimColor,
    error = errorLight,
    onError = onErrorLight,
    errorContainer = errorContainerLight,
    onErrorContainer = onErrorContainerLight,
    inverseSurface = light.inverseSurface,
    inverseOnSurface = light.inverseOnSurface,
    inversePrimary = dark.primary,
    surfaceDim = light.surfaceDim,
    surfaceBright = light.surfaceBright,
    surfaceContainerLowest = light.surfaceContainerLowest,
    surfaceContainerLow = light.surfaceContainerLow,
    surfaceContainer = light.surfaceContainer,
    surfaceContainerHigh = light.surfaceContainerHigh,
    surfaceContainerHighest = light.surfaceContainerHighest,
)

internal fun ThemePalette.toDarkColorScheme(): ColorScheme = darkColorScheme(
    primary = dark.primary,
    onPrimary = dark.onPrimary,
    primaryContainer = dark.primaryContainer,
    onPrimaryContainer = dark.onPrimaryContainer,
    secondary = dark.secondary,
    onSecondary = dark.onSecondary,
    secondaryContainer = dark.secondaryContainer,
    onSecondaryContainer = dark.onSecondaryContainer,
    tertiary = dark.tertiary,
    onTertiary = dark.onTertiary,
    tertiaryContainer = dark.tertiaryContainer,
    onTertiaryContainer = dark.onTertiaryContainer,
    background = dark.background,
    onBackground = dark.onBackground,
    surface = dark.surface,
    onSurface = dark.onSurface,
    surfaceVariant = dark.surfaceVariant,
    onSurfaceVariant = dark.onSurfaceVariant,
    outline = dark.outline,
    outlineVariant = dark.outlineVariant,
    scrim = scrimColor,
    error = errorDark,
    onError = onErrorDark,
    errorContainer = errorContainerDark,
    onErrorContainer = onErrorContainerDark,
    inverseSurface = dark.inverseSurface,
    inverseOnSurface = dark.inverseOnSurface,
    inversePrimary = light.primary,
    surfaceDim = dark.surfaceDim,
    surfaceBright = dark.surfaceBright,
    surfaceContainerLowest = dark.surfaceContainerLowest,
    surfaceContainerLow = dark.surfaceContainerLow,
    surfaceContainer = dark.surfaceContainer,
    surfaceContainerHigh = dark.surfaceContainerHigh,
    surfaceContainerHighest = dark.surfaceContainerHighest,
)

internal fun ThemePalette.toColorScheme(isDark: Boolean): ColorScheme {
    return if (isDark) toDarkColorScheme() else toLightColorScheme()
}
